### ISSUE TITLE
SCME doesn't compile with ifort<16.0

### ISSUE THREAD

**Issue by tdaff** [libAtoms/QUIP#78]
```
/scratch/quip/QUIP/src/ThirdParty/scme/src/localAxes_mod.f90 -o localAxes_mod.o
/scratch/quip/QUIP/src/ThirdParty/scme/src/localAxes_mod.f90(62): error #6263: This intrinsic function is invalid in constant expressions.   [SUM]
 real(dp), parameter :: m(3) = [1.0_dp, 1.0_dp, 16.0_dp], Mm = sum(m) !are these in the right units???
---------------------------------------------------------------^
```

Apparently the use of ``sum`` is valid in F2003, but is not implemented until the most recent Intel compiler versions.

**Comment by tdaff** [comment]
Also fails with gfortran-4.4

```
Error: transformational intrinsic 'sum' at (1) is not permitted in an initialization expression
```

But after looking at the code rather than copy-pasting, it seems to be easy to replace with just ``Mm = 18.0_dp``...

**Comment by tdaff** [comment]
Fixed in ThirdParty
